export const siteConfig = {
  title: 'Widgets y Componentes UI con Tailwind CSS 4',
  description: 'Explora una colección de widgets, componentes y diseños minimalistas creados con Tailwind CSS 4 y Astro. Recursos modernos y personalizables para proyectos de finanzas, redes sociales, deportes, viajes y más.',
  keywords: [
    'componentes',
    'astro',
    'tailwind',
    'galería de widgets',
    'ui',
    'widgets para dashboards',
    'plantillas tailwind css',
    'widgets adaptativos',
    'componentes para desarrolladores',
    'interfaz limpia',
    'widgets para aplicaciones web',
    'recursos tailwind css 4',
    'javascript',
    'css',
    'html',
    'ux',
    'ui',
    'astro'
  ],
  author: {
    name: 'Frank Esteban',
    alternateName: 'FrankUXUI',
  },
  ogImage: '/og.jpg',
  logo: '/frankuxui_frontend_developer_ux_ui_designer_logo.png',
  social: {
    github: 'https://github.com/frankuxui',
    linkedin: 'https://www.linkedin.com/in/frankuxui',
    figma: 'https://www.figma.com/@frankuxui',
    codepen: 'https://codepen.io/frankuxui',
    codesandbox: 'https://codesandbox.io/u/frankuxui',
    instagram: 'https://instagram.com/frankuxui',
    dribbble: 'https://dribbble.com/frankuxui',
    tailwindComponents: 'https://www.creative-tim.com/twcomponents/u/frankuxui',
    devto: 'https://dev.to/frankuxui',
  }
}